### ISSUE TITLE
Question about softmax_loss_layer

### ISSUE THREAD

**Issue by chenxia-han** [daijifeng001/caffe-rfcn#3]
Hi, I find two extra lines in **softmax_loss_layer.cpp** 

`// Fix a bug which occurs with more than one output`
`softmax_param.clear_loss_weight();`

And I'm not sure why you add these or what will happen if I delete these two lines.

**Comment by xiaoxiongli** [comment]
i am sure that you delete first line is ok, because it is a comment in C plus plus.

**Comment by liyi14** [comment]
It will leads to a loss_weights number mismatch error if remove these two lines, since the _modified_ SoftmaxWithLoss layer may have 3 loss_weights while it is limited no more than 2 in softmax_param.
